### PR TITLE
hcp.md edits

### PR DESCRIPTION
**Pull request by begim-f**
Made edits to the hcp.md files

### CODE REVIEW

**Review by rosemccollum — COMMENTED** [review]
For the NDA Uploads section in mkdocs.yml, I'm not sure how readthedocs will interpret that, not sure if you can have a subsection within a section. 
@audreymhoughton is this what were you thinking or did you just want a single NDA page with subsections?

**Comment by audreymhoughton** [comment]
@rosemccollum @begim-f - whatever makes the most sense to you all!

**Review by rosemccollum — CHANGES_REQUESTED** [review]
@begim-f I think it makes more sense to have one NDA page with the other sections as subpages (requesting archive, collections, validating uploads) Can you merge those three file into one page?

**Review by rosemccollum — APPROVED** [review]
Thanks Begim!

**Review by audreymhoughton — APPROVED** [review]

**Pull request merged**
